config/routes.rb
GetSomeMusic::Application.routes.draw do
  
  post "admindash/social"
  post "admindash/financial"
  post "transactions/notify"
  get "transactions/show"
  get "transactions/subscribe"
  get "albums/create"
  get "albums/destroy"
  get "albums/view"
  get "songs/create"
  get "songs/destroy"
  get "songs/edit"
  get "songs/update"
  get "credits/create"
  get "credits/update"
  get "purchases/create"
  get "purchases/displayall"
  get "purchases/destroy"
  get "banddash/destroy"
  get "home/index"
  get "home/download"
  get "home/search"
  
  
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login"}
  
  resources :users do
    resources :purchases, :only => [:create, :destroy]
    resources :band, :only => [:create, :destroy] 
  end
  
  resources :albums
  resources :credits
  resources :songs
  resources :transactions
  
  resources :banddash, :only => [:index, :create, :destroy, :show]
  resources :userdash, :only => [:index]
  resources :admindash, :only => [:index]
  
  root :to => 'home#index'
end

app/controllers/userdash_controller.rb
class UserdashController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    session[:trail] ||= Array.new
    

    if session[:trail].first != url_for(:only_path => true)
      session[:trail].push(url_for(:only_path => true))
    end
    
    if session[:trail].size > 4
      session[:trail].delete_at(0)
    end
    
    if current_user.role != "user"
      redirect_to root_path, notice: 'Sorry, the resource you tried to access is only available to registered clients of the website. If you are a band or not registered you will not have access to this webpage.'
    end
  end
  
end

app/helpers/userdash_helper.rb
module UserdashHelper
end

app/views/userdash/index.html.erb
<h2>Welcome to your dashboard</h2><br/>
<h4>My songs<small style="padding-left:20px;">Total songs bought: <%= current_user.purchases.count %></small></h4>
<table class="table table-hover" id="usrSongs">
  <tr class="info"><td>Band</td><td>Song</td><td>Price</td><td>Purchased</td><td>Download</td></tr>
  <% if !current_user.purchases.first.nil? %>
    <% current_user.purchases.last(5).each do |p| %>
    <tr>
      <% @song = Song.find(p.song_id) %>
      <td><%= @song.band.name %></td>
      <td><%= @song.name %></td>
      <td><%= number_with_precision((p.value.to_f / 100), :precision => 2) %></td>
      <td><%= p.created_at.strftime("%d %b %Y") %></td>
      <td><%= link_to 'Download', home_download_path(:sid => @song.id) %></td>
    </tr>
    <% end %>
  <% end %>
</table>
<div>
<% if !current_user.purchases.first.nil? %>
  <button id="btnAllSongs" class="btn btn-large btn-block btn-info" onclick="displayAllSongs();">Load all my songs</button>
  <br/>
  <hr/>
  
  <% @purchases = current_user.purchases %>
  <h4>My tags</h4>
  <% @tags = Array.new %>
  
  <% @purchases.each do |p| %>
    <% Song.find(p.song_id).tag_list.each do |tag| %>
      <% @tags << tag %>
    <% end %>
  <% end %>
  <% if !@tags.nil? %>
    <% @tags.uniq.each do |tag| %>
      <span style="line-height: 40px;margin-right: 30px;padding: 4px 10px;font-size: 17px;" class="badge badge-important"><%= tag %></span>
    <% end %>    
  <% end %>    
      
  <h4>My Bands</h4>
  <% @bands = Array.new %><% @purchases.each do |p| %>
    <% @band = Band.find(Song.find(p.song_id).band_id) %>
      <% @bands << @band %>
    <% end %>
  <% end %>
  <% if !@bands.nil? %>
    <% @bands.uniq.each do |band| %>
      <span style="line-height: 50px;margin-right: 30px;padding: 4px 10px;font-size: 27px;" class="badge badge-inverse"><a style="color:white" href="/banddash/<%= band.id %>"><%= band.name %></a></span>
    <% end %>
  <% end %>
  <br/>
</div>
  