config/routes.rb
GetSomeMusic::Application.routes.draw do
  
  post "admindash/social"
  post "admindash/financial"
  post "transactions/notify"
  get "transactions/show"
  get "transactions/subscribe"
  get "albums/create"
  get "albums/destroy"
  get "albums/view"
  get "songs/create"
  get "songs/destroy"
  get "songs/edit"
  get "songs/update"
  get "credits/create"
  get "credits/update"
  get "purchases/create"
  get "purchases/displayall"
  get "purchases/destroy"
  get "banddash/destroy"
  get "home/index"
  get "home/download"
  get "home/search"
  
  
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login"}
  
  resources :users do
    resources :purchases, :only => [:create, :destroy]
    resources :band, :only => [:create, :destroy] 
  end
  
  resources :albums
  resources :credits
  resources :songs
  resources :transactions
  
  resources :banddash, :only => [:index, :create, :destroy, :show]
  resources :userdash, :only => [:index]
  resources :admindash, :only => [:index]
  
  root :to => 'home#index'
end

app/controllers/banddash_controller.rb
class BanddashController < ApplicationController

  before_filter :authenticate_user!
    
  def index
    session[:trail] ||= Array.new
    
    if session[:trail].size > 4
      session[:trail].delete_at(0)
    end
    
    if session[:trail].first != url_for(:only_path => true)
      session[:trail].push(url_for(:only_path => true))
    end
  end
  
  def create
    if current_user.band.nil?
      @band = Band.new
      @band.name = params[:band][:name]
      @band.members = params[:band][:members]
      @band.user_id = current_user.id
      @band.individual_artist = params[:band][:individual_artist]
      @band.earned = 0
      @band.earned_company = 0
      @band.subscription = Subscription.new
      @band.subscription.user_id = current_user.id
      @band.subscription.total_purchased = 0;
      @band.subscription.expires = Time.now
      
      if @band.save and @band.subscription.save
        redirect_to banddash_index_path
      else
        redirect_to banddash_index_path, notice: 'Successfully created your band!'      
      end
    else
        redirect_to banddash_index_path, notice: 'An error occured.'
    end
  end
  
  def destroy
    if current_user.band.destroy
      redirect_to banddash_index_path, notice: 'Successfully deleted your band!'
    else
      redirect_to banddash_index_path, notice: 'An error occured.'     
    end
  end
  
  def show
    @band = Band.find(params[:id])
  end
end

app/helpers/banddash_helper.rb
module BanddashHelper
end

app/views/banddash/index.html.erb
<h2>Your Band's dashboard</h2>
<div>
  <% if current_user.band.nil? %>
    <% @band = Band.new %>
    <%= form_for @band, :url => { :action => "create" } do |f| %>
      <%= f.text_field :name, :placeholder => "Band Name" %><br/>
      <%= f.text_field :members, :placeholder => "Number of members" %><br/>
      Individual artist? <%= f.check_box :individual_artist %><br/>
      <%= f.submit 'Create Band', :class => "btn btn-success", :style => 'margin-top:7px;'%>  
    <% end %>
  <% else %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">×</button>
        <form id="updateBand" style="display:none">
          <div class="input-prepend">
            <span class="add-on" style="color:#669">Band Name</span>
            <input class="span2" id="prependedInput" size="16" type="text" placeholder="<%= current_user.band.name %>">
          </div>
          <div class="input-prepend">
            <span class="add-on" style="color:#669">Band Members</span>
            <input class="span2" id="prependedInput" size="16" type="text" placeholder="<%= current_user.band.members %>">
          </div>
          <button class="btn btn-warning" type="button">Update band</button>
          <button type="button" onclick="bandAllowUpdate();" class="btn btn-danger">Cancel</button> 
        </form>
        <div id="bandDetails">
          Band ID: <%= current_user.band.id %><br/>
          Band name: <%= current_user.band.name %><br/>
          Songs published: <%= Band.find(current_user.band.id).songs.size %><br/>
          <button style="margin-top:7px;" onclick="bandDetailShow();" class="btn btn-warning">Edit band details</button>    
        </div>
    </div>
  <% end %>
</div><br/>

<% if !current_user.band.nil? %>
  <div>
    <h3>Tracks</h3>
    <table class="table table-striped">
      <tr class="info">
        <td>Track Name</td>
        <td>Sales (#)</td>
        <td>Edit</td>
        <td>Delete</td>
      </tr>
      <% current_user.band.songs.each do |track| %>    
      <tr>
        <td><%= track.name %></td>
        <td><%= track.sales %></td>
        <td><%= link_to 'Edit', edit_song_path(track), :class => 'btn btn-warning', :style => 'margin:0px;padding:0px 10px' %></td>
        <td><%= link_to 'Delete', track, :method => :delete, :confirm => "Are you sure?" ,:class => 'btn btn-danger', :style => 'margin:0px;padding:0px 10px' %></td>
      </tr>
      <% end %>
    </table>
    <% if current_user.band.has_subscription(current_user.band) %>
    <button id="btnTrack" style="margin-bottom:10px;" class="btn btn-success" onclick="btnTrack();">Create a new track</button>
      <div id="newTrack" style="display:none;">
        <%= form_for Song.new, :html => { :multipart => true } do |f| %>
          <%= f.text_field :name, :placeholder => "Song name" %><br/>
          <%= f.text_field :cost, :placeholder => "Cost ( £ )" %><br/>
          <%= f.text_field :tag_list, :placeholder => "Tags, separated by commas" %><br/>
          mp3 file: <%= f.file_field :mp3 %><br/>&nbsp;&nbsp;
          <button type="button" onclick="showLoadModal();activateRumble();" class="btn btn-success">Upload new track</button>
          <button type="button" class="btn btn-danger">Cancel</button>    
        <% end %>
      </div>
    <% else %>
      <div class="alert alert-error">
        <h4>Subscribe to sell!</h4>
        <h5 style="color:black">In order to upload new songs and have your songs displayed on the purchase list
          you need to subscribe to GetSomeMusic!</h5>
        <h5 style="color:black">To purchase a 3 month subscription please click the subscribe button bellow. 
          <small style="color:black">You will have to pay a one time charge of £30 for a <strong>three month</strong> subscription.</small></h5>
        
        <% if !current_user.band.nil? %>
          <%= form_for Transaction.new do |f| %>
            <%= f.hidden_field :sub, :value => 'q4DaFUbr' %>
            <button type="submit" class="btn btn-success">Subscribe (3 months)</button>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %><br/>

<h3>Albums<small style="margin-left:20px;">click the album titles to show/hide their contents</small></h3>
<% @temp_song = Song.new %>
<% current_user.albums.each do |album| %>
  <div id="album<%= album.id %>" class="album" onclick="$('#albumInner<%= album.id %> ').slideToggle();">
    <div class="albumArt"><% if !album.coverart.content_type.nil? %><%= image_tag 'https://dl.dropbox.com/u/24593987/' + album.coverart_file_name, :size => "40x40" %>&nbsp;<% end %></div>
    <h4><%= album.name %></h4>
    <div id="albumInner<%= album.id %>" style="display:none;">
      <div>
        <table class="table">
        <% album.songs.each do |track| %>
          <tr><td><%= track.name %><td/><tr/>
        <% end %>
        </table>
      </div>
      <div>
        <%= form_for @temp_song, :url => url_for(:controller => 'songs', :action => 'update'), :html=>{:method=>:put} do |sf| %>
          <select name="song[id]">
            <% current_user.band.songs.each do |current_song| %>
            <option name="id2" value="<%= current_song.id %>"><%= current_song.name %></option>
            <% end %>
          </select>
          <%= sf.hidden_field :album_id, :value => album.id %>
          <%= sf.submit 'Add song to album', :class => "btn btn-success", :style => "margin-left:20px;margin-top:-9px" %>
        <% end %> 
      </div>
    </div>
  </div><br/>
<% end %>

<% if !current_user.band.nil? %>
  <div id="addAlbum">
    <h4>Create a new album</h4>
    <% @album = Album.new %>
    <%= form_for(@album, :html => { :multipart => true }) do |f| %>
      <% if @album.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>
          <ul>
          <% @album.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :name, :placeholder => "Album name" %>
      <%= f.submit 'Create album', :class => "btn btn-success", :style => "margin-left:20px;margin-top:-7px" %><br/>
      Album Cover: <%= f.file_field :coverart %>
      <%= f.hidden_field :band_id, :value => current_user.band.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
    <% end %>
  </div>
<% end %><br/>

<div style="position:fixed;width:700px;padding:30px;margin-top: -140px;box-shadow: none;outline:none;border:0px;background-color: transparent;color:white;" id="loadingModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="loadingModalLabel" aria-hidden="true">
  <div id="lodd" class="modal-body">
    <h1 style="font-size: 132px">Loading…</h1>
  </div>
</div>
<script type="text/javascript" src="https://jackrugile.com/jrumble/js/jrumble.1.1.min.js"></script>

app/views/banddash/show.html.erb
<h2><%= @band.name %></h2>

<h3>All our songs</h3>
<table class="table table-hover table-striped">
  <tr class="info"><td>Song</td><td>Published</td><td>Downloaded</td><td>View</td></tr>
  <% @band.songs.each do |track| %>
    <tr>
      <td><%= track.name %></td>
      <td><%= track.created_at.strftime("%d %b %y") %></td>
      <td><%= track.sales %> times</td>
      <td><a href="/songs/<%= track.id %>"><%= image_tag '/assets/eye.png', :size => "35x30", :id => "show" %></a></td>
    </tr>
  <% end %>
</table>

<div id="bandInfo">
  <h3>About our band</h3>
  <p>
    We have <%= @band.members %> members in our band.
  </p>
</div>